name: CI
on:
    push:
        branches: [develop, main]
    pull_request:
        branches: [develop, main]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install modules
              run: npm install
            - name: Run ESLint
              run: npx eslint . --ext .js,.jsx,.ts,.tsx
